{"name": "test_delete_project", "status": "failed", "statusDetails": {"message": "AssertionError: test_delete_project/then: Project is not found. Check Project key again\nassert False", "trace": "fixturefunc = <function verify_deleted_project at 0x000001FEA1259080>, request = <FixtureRequest for <Function test_delete_project>>, kwargs = {'context': namespace(response=404)}\n\n    def call_fixture_func(\n        fixturefunc: \"_FixtureFunc[FixtureValue]\", request: FixtureRequest, kwargs\n    ) -> FixtureValue:\n        if is_generator(fixturefunc):\n            fixturefunc = cast(\n                Callable[..., Generator[FixtureValue, None, None]], fixturefunc\n            )\n            generator = fixturefunc(**kwargs)\n            try:\n                fixture_result = next(generator)\n            except StopIteration:\n                raise ValueError(f\"{request.fixturename} did not yield a value\") from None\n            finalizer = functools.partial(_teardown_yield_fixture, fixturefunc, generator)\n            request.addfinalizer(finalizer)\n        else:\n            fixturefunc = cast(Callable[..., FixtureValue], fixturefunc)\n>           fixture_result = fixturefunc(**kwargs)\n\n.venv\\Lib\\site-packages\\_pytest\\fixtures.py:902: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\ncontext = namespace(response=404)\n\n    @then(\"project should get deleted\")\n    def verify_deleted_project(context:SimpleNamespace):\n        response=context.response\n        print(f\"test_delete_project/then: This is response of context in then: {response}\")\n        if response in [200,204]:\n            assert True\n        elif response==404:\n>           assert False,f\"test_delete_project/then: Project is not found. Check Project key again\"\nE           AssertionError: test_delete_project/then: Project is not found. Check Project key again\nE           assert False\n\ntests\\test_jira_project.py:82: AssertionError"}, "description": "../features/test.feature: Delete a Project", "attachments": [{"name": "log", "source": "6e135eb7-069f-443a-905a-75caf02258a6-attachment.txt", "type": "text/plain"}], "start": 1744605341611, "stop": 1744605342092, "uuid": "52be962a-a312-40b3-9dbd-0c766820bbaf", "historyId": "afb51e02d66e9a2de921b62e5c262d5f", "testCaseId": "afb51e02d66e9a2de921b62e5c262d5f", "fullName": "tests.test_jira_project#test_delete_project", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_jira_project"}, {"name": "host", "value": "user"}, {"name": "thread", "value": "25892-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_jira_project"}]}